// Code generated by entc, DO NOT EDIT.

package migrationinfo

import (
	"time"
)

const (
	// Label holds the string label denoting the migrationinfo type in the database.
	Label = "migration_info"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldIsMigrated holds the string denoting the is_migrated field in the database.
	FieldIsMigrated = "is_migrated"
	// Table holds the table name of the migrationinfo in the database.
	Table = "migration_infos"
)

// Columns holds all SQL columns for migrationinfo fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldIsMigrated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultIsMigrated holds the default value on creation for the "is_migrated" field.
	DefaultIsMigrated bool
)
