---
- name: Update and upgrade the machine
  apt:
    upgrade: dist
    update_cache: true

- name: install apt packages
  apt:
    name: '{{item}}'
    state: present
    update_cache: yes
  loop:
    - acl

- name: install node_exporter
  import_tasks: node_exporter.yml

- name: install promtail
  import_tasks: promtail.yml

- name: firewall setup
  import_tasks: firewall.yml
