// Code generated by entc, DO NOT EDIT.

package chain

import (
	"time"
)

const (
	// Label holds the string label denoting the chain type in the database.
	Label = "chain"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldIsEnabled holds the string denoting the is_enabled field in the database.
	FieldIsEnabled = "is_enabled"
	// EdgeProposals holds the string denoting the proposals edge name in mutations.
	EdgeProposals = "proposals"
	// EdgeTelegramChats holds the string denoting the telegram_chats edge name in mutations.
	EdgeTelegramChats = "telegram_chats"
	// EdgeDiscordChannels holds the string denoting the discord_channels edge name in mutations.
	EdgeDiscordChannels = "discord_channels"
	// Table holds the table name of the chain in the database.
	Table = "chains"
	// ProposalsTable is the table that holds the proposals relation/edge.
	ProposalsTable = "proposals"
	// ProposalsInverseTable is the table name for the Proposal entity.
	// It exists in this package in order to avoid circular dependency with the "proposal" package.
	ProposalsInverseTable = "proposals"
	// ProposalsColumn is the table column denoting the proposals relation/edge.
	ProposalsColumn = "chain_proposals"
	// TelegramChatsTable is the table that holds the telegram_chats relation/edge. The primary key declared below.
	TelegramChatsTable = "telegram_chat_chains"
	// TelegramChatsInverseTable is the table name for the TelegramChat entity.
	// It exists in this package in order to avoid circular dependency with the "telegramchat" package.
	TelegramChatsInverseTable = "telegram_chats"
	// DiscordChannelsTable is the table that holds the discord_channels relation/edge. The primary key declared below.
	DiscordChannelsTable = "discord_channel_chains"
	// DiscordChannelsInverseTable is the table name for the DiscordChannel entity.
	// It exists in this package in order to avoid circular dependency with the "discordchannel" package.
	DiscordChannelsInverseTable = "discord_channels"
)

// Columns holds all SQL columns for chain fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldDisplayName,
	FieldIsEnabled,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "chains"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"wallet_chains",
}

var (
	// TelegramChatsPrimaryKey and TelegramChatsColumn2 are the table columns denoting the
	// primary key for the telegram_chats relation (M2M).
	TelegramChatsPrimaryKey = []string{"telegram_chat_id", "chain_id"}
	// DiscordChannelsPrimaryKey and DiscordChannelsColumn2 are the table columns denoting the
	// primary key for the discord_channels relation (M2M).
	DiscordChannelsPrimaryKey = []string{"discord_channel_id", "chain_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultIsEnabled holds the default value on creation for the "is_enabled" field.
	DefaultIsEnabled bool
)
