// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shifty11/cosmos-gov/ent/lenschaininfo"
	"github.com/shifty11/cosmos-gov/ent/predicate"
)

// LensChainInfoDelete is the builder for deleting a LensChainInfo entity.
type LensChainInfoDelete struct {
	config
	hooks    []Hook
	mutation *LensChainInfoMutation
}

// Where appends a list predicates to the LensChainInfoDelete builder.
func (lcid *LensChainInfoDelete) Where(ps ...predicate.LensChainInfo) *LensChainInfoDelete {
	lcid.mutation.Where(ps...)
	return lcid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lcid *LensChainInfoDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(lcid.hooks) == 0 {
		affected, err = lcid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LensChainInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lcid.mutation = mutation
			affected, err = lcid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lcid.hooks) - 1; i >= 0; i-- {
			if lcid.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lcid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lcid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcid *LensChainInfoDelete) ExecX(ctx context.Context) int {
	n, err := lcid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lcid *LensChainInfoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: lenschaininfo.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: lenschaininfo.FieldID,
			},
		},
	}
	if ps := lcid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, lcid.driver, _spec)
}

// LensChainInfoDeleteOne is the builder for deleting a single LensChainInfo entity.
type LensChainInfoDeleteOne struct {
	lcid *LensChainInfoDelete
}

// Exec executes the deletion query.
func (lcido *LensChainInfoDeleteOne) Exec(ctx context.Context) error {
	n, err := lcido.lcid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{lenschaininfo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lcido *LensChainInfoDeleteOne) ExecX(ctx context.Context) {
	lcido.lcid.ExecX(ctx)
}
