// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shifty11/cosmos-gov/ent/lenschaininfo"
	"github.com/shifty11/cosmos-gov/ent/predicate"
)

// LensChainInfoQuery is the builder for querying LensChainInfo entities.
type LensChainInfoQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.LensChainInfo
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LensChainInfoQuery builder.
func (lciq *LensChainInfoQuery) Where(ps ...predicate.LensChainInfo) *LensChainInfoQuery {
	lciq.predicates = append(lciq.predicates, ps...)
	return lciq
}

// Limit adds a limit step to the query.
func (lciq *LensChainInfoQuery) Limit(limit int) *LensChainInfoQuery {
	lciq.limit = &limit
	return lciq
}

// Offset adds an offset step to the query.
func (lciq *LensChainInfoQuery) Offset(offset int) *LensChainInfoQuery {
	lciq.offset = &offset
	return lciq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lciq *LensChainInfoQuery) Unique(unique bool) *LensChainInfoQuery {
	lciq.unique = &unique
	return lciq
}

// Order adds an order step to the query.
func (lciq *LensChainInfoQuery) Order(o ...OrderFunc) *LensChainInfoQuery {
	lciq.order = append(lciq.order, o...)
	return lciq
}

// First returns the first LensChainInfo entity from the query.
// Returns a *NotFoundError when no LensChainInfo was found.
func (lciq *LensChainInfoQuery) First(ctx context.Context) (*LensChainInfo, error) {
	nodes, err := lciq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{lenschaininfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lciq *LensChainInfoQuery) FirstX(ctx context.Context) *LensChainInfo {
	node, err := lciq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LensChainInfo ID from the query.
// Returns a *NotFoundError when no LensChainInfo ID was found.
func (lciq *LensChainInfoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lciq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{lenschaininfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lciq *LensChainInfoQuery) FirstIDX(ctx context.Context) int {
	id, err := lciq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LensChainInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LensChainInfo entity is found.
// Returns a *NotFoundError when no LensChainInfo entities are found.
func (lciq *LensChainInfoQuery) Only(ctx context.Context) (*LensChainInfo, error) {
	nodes, err := lciq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{lenschaininfo.Label}
	default:
		return nil, &NotSingularError{lenschaininfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lciq *LensChainInfoQuery) OnlyX(ctx context.Context) *LensChainInfo {
	node, err := lciq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LensChainInfo ID in the query.
// Returns a *NotSingularError when more than one LensChainInfo ID is found.
// Returns a *NotFoundError when no entities are found.
func (lciq *LensChainInfoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lciq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{lenschaininfo.Label}
	default:
		err = &NotSingularError{lenschaininfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lciq *LensChainInfoQuery) OnlyIDX(ctx context.Context) int {
	id, err := lciq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LensChainInfos.
func (lciq *LensChainInfoQuery) All(ctx context.Context) ([]*LensChainInfo, error) {
	if err := lciq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return lciq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (lciq *LensChainInfoQuery) AllX(ctx context.Context) []*LensChainInfo {
	nodes, err := lciq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LensChainInfo IDs.
func (lciq *LensChainInfoQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := lciq.Select(lenschaininfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lciq *LensChainInfoQuery) IDsX(ctx context.Context) []int {
	ids, err := lciq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lciq *LensChainInfoQuery) Count(ctx context.Context) (int, error) {
	if err := lciq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return lciq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (lciq *LensChainInfoQuery) CountX(ctx context.Context) int {
	count, err := lciq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lciq *LensChainInfoQuery) Exist(ctx context.Context) (bool, error) {
	if err := lciq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return lciq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (lciq *LensChainInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := lciq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LensChainInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lciq *LensChainInfoQuery) Clone() *LensChainInfoQuery {
	if lciq == nil {
		return nil
	}
	return &LensChainInfoQuery{
		config:     lciq.config,
		limit:      lciq.limit,
		offset:     lciq.offset,
		order:      append([]OrderFunc{}, lciq.order...),
		predicates: append([]predicate.LensChainInfo{}, lciq.predicates...),
		// clone intermediate query.
		sql:    lciq.sql.Clone(),
		path:   lciq.path,
		unique: lciq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LensChainInfo.Query().
//		GroupBy(lenschaininfo.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (lciq *LensChainInfoQuery) GroupBy(field string, fields ...string) *LensChainInfoGroupBy {
	group := &LensChainInfoGroupBy{config: lciq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := lciq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return lciq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.LensChainInfo.Query().
//		Select(lenschaininfo.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (lciq *LensChainInfoQuery) Select(fields ...string) *LensChainInfoSelect {
	lciq.fields = append(lciq.fields, fields...)
	return &LensChainInfoSelect{LensChainInfoQuery: lciq}
}

func (lciq *LensChainInfoQuery) prepareQuery(ctx context.Context) error {
	for _, f := range lciq.fields {
		if !lenschaininfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lciq.path != nil {
		prev, err := lciq.path(ctx)
		if err != nil {
			return err
		}
		lciq.sql = prev
	}
	return nil
}

func (lciq *LensChainInfoQuery) sqlAll(ctx context.Context) ([]*LensChainInfo, error) {
	var (
		nodes = []*LensChainInfo{}
		_spec = lciq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &LensChainInfo{config: lciq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, lciq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (lciq *LensChainInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lciq.querySpec()
	_spec.Node.Columns = lciq.fields
	if len(lciq.fields) > 0 {
		_spec.Unique = lciq.unique != nil && *lciq.unique
	}
	return sqlgraph.CountNodes(ctx, lciq.driver, _spec)
}

func (lciq *LensChainInfoQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := lciq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (lciq *LensChainInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   lenschaininfo.Table,
			Columns: lenschaininfo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: lenschaininfo.FieldID,
			},
		},
		From:   lciq.sql,
		Unique: true,
	}
	if unique := lciq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := lciq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lenschaininfo.FieldID)
		for i := range fields {
			if fields[i] != lenschaininfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lciq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lciq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lciq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lciq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lciq *LensChainInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lciq.driver.Dialect())
	t1 := builder.Table(lenschaininfo.Table)
	columns := lciq.fields
	if len(columns) == 0 {
		columns = lenschaininfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lciq.sql != nil {
		selector = lciq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lciq.unique != nil && *lciq.unique {
		selector.Distinct()
	}
	for _, p := range lciq.predicates {
		p(selector)
	}
	for _, p := range lciq.order {
		p(selector)
	}
	if offset := lciq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lciq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LensChainInfoGroupBy is the group-by builder for LensChainInfo entities.
type LensChainInfoGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lcigb *LensChainInfoGroupBy) Aggregate(fns ...AggregateFunc) *LensChainInfoGroupBy {
	lcigb.fns = append(lcigb.fns, fns...)
	return lcigb
}

// Scan applies the group-by query and scans the result into the given value.
func (lcigb *LensChainInfoGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := lcigb.path(ctx)
	if err != nil {
		return err
	}
	lcigb.sql = query
	return lcigb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (lcigb *LensChainInfoGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := lcigb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (lcigb *LensChainInfoGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(lcigb.fields) > 1 {
		return nil, errors.New("ent: LensChainInfoGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := lcigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (lcigb *LensChainInfoGroupBy) StringsX(ctx context.Context) []string {
	v, err := lcigb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lcigb *LensChainInfoGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = lcigb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lenschaininfo.Label}
	default:
		err = fmt.Errorf("ent: LensChainInfoGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (lcigb *LensChainInfoGroupBy) StringX(ctx context.Context) string {
	v, err := lcigb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (lcigb *LensChainInfoGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(lcigb.fields) > 1 {
		return nil, errors.New("ent: LensChainInfoGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := lcigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (lcigb *LensChainInfoGroupBy) IntsX(ctx context.Context) []int {
	v, err := lcigb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lcigb *LensChainInfoGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = lcigb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lenschaininfo.Label}
	default:
		err = fmt.Errorf("ent: LensChainInfoGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (lcigb *LensChainInfoGroupBy) IntX(ctx context.Context) int {
	v, err := lcigb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (lcigb *LensChainInfoGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(lcigb.fields) > 1 {
		return nil, errors.New("ent: LensChainInfoGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := lcigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (lcigb *LensChainInfoGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := lcigb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lcigb *LensChainInfoGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = lcigb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lenschaininfo.Label}
	default:
		err = fmt.Errorf("ent: LensChainInfoGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (lcigb *LensChainInfoGroupBy) Float64X(ctx context.Context) float64 {
	v, err := lcigb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (lcigb *LensChainInfoGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(lcigb.fields) > 1 {
		return nil, errors.New("ent: LensChainInfoGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := lcigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (lcigb *LensChainInfoGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := lcigb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lcigb *LensChainInfoGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = lcigb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lenschaininfo.Label}
	default:
		err = fmt.Errorf("ent: LensChainInfoGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (lcigb *LensChainInfoGroupBy) BoolX(ctx context.Context) bool {
	v, err := lcigb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (lcigb *LensChainInfoGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range lcigb.fields {
		if !lenschaininfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := lcigb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lcigb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (lcigb *LensChainInfoGroupBy) sqlQuery() *sql.Selector {
	selector := lcigb.sql.Select()
	aggregation := make([]string, 0, len(lcigb.fns))
	for _, fn := range lcigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(lcigb.fields)+len(lcigb.fns))
		for _, f := range lcigb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(lcigb.fields...)...)
}

// LensChainInfoSelect is the builder for selecting fields of LensChainInfo entities.
type LensChainInfoSelect struct {
	*LensChainInfoQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (lcis *LensChainInfoSelect) Scan(ctx context.Context, v interface{}) error {
	if err := lcis.prepareQuery(ctx); err != nil {
		return err
	}
	lcis.sql = lcis.LensChainInfoQuery.sqlQuery(ctx)
	return lcis.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (lcis *LensChainInfoSelect) ScanX(ctx context.Context, v interface{}) {
	if err := lcis.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (lcis *LensChainInfoSelect) Strings(ctx context.Context) ([]string, error) {
	if len(lcis.fields) > 1 {
		return nil, errors.New("ent: LensChainInfoSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := lcis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (lcis *LensChainInfoSelect) StringsX(ctx context.Context) []string {
	v, err := lcis.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (lcis *LensChainInfoSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = lcis.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lenschaininfo.Label}
	default:
		err = fmt.Errorf("ent: LensChainInfoSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (lcis *LensChainInfoSelect) StringX(ctx context.Context) string {
	v, err := lcis.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (lcis *LensChainInfoSelect) Ints(ctx context.Context) ([]int, error) {
	if len(lcis.fields) > 1 {
		return nil, errors.New("ent: LensChainInfoSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := lcis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (lcis *LensChainInfoSelect) IntsX(ctx context.Context) []int {
	v, err := lcis.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (lcis *LensChainInfoSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = lcis.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lenschaininfo.Label}
	default:
		err = fmt.Errorf("ent: LensChainInfoSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (lcis *LensChainInfoSelect) IntX(ctx context.Context) int {
	v, err := lcis.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (lcis *LensChainInfoSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(lcis.fields) > 1 {
		return nil, errors.New("ent: LensChainInfoSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := lcis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (lcis *LensChainInfoSelect) Float64sX(ctx context.Context) []float64 {
	v, err := lcis.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (lcis *LensChainInfoSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = lcis.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lenschaininfo.Label}
	default:
		err = fmt.Errorf("ent: LensChainInfoSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (lcis *LensChainInfoSelect) Float64X(ctx context.Context) float64 {
	v, err := lcis.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (lcis *LensChainInfoSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(lcis.fields) > 1 {
		return nil, errors.New("ent: LensChainInfoSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := lcis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (lcis *LensChainInfoSelect) BoolsX(ctx context.Context) []bool {
	v, err := lcis.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (lcis *LensChainInfoSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = lcis.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lenschaininfo.Label}
	default:
		err = fmt.Errorf("ent: LensChainInfoSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (lcis *LensChainInfoSelect) BoolX(ctx context.Context) bool {
	v, err := lcis.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (lcis *LensChainInfoSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := lcis.sql.Query()
	if err := lcis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
