// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shifty11/cosmos-gov/ent/predicate"
	"github.com/shifty11/cosmos-gov/ent/rpcendpoint"
)

// RpcEndpointDelete is the builder for deleting a RpcEndpoint entity.
type RpcEndpointDelete struct {
	config
	hooks    []Hook
	mutation *RpcEndpointMutation
}

// Where appends a list predicates to the RpcEndpointDelete builder.
func (red *RpcEndpointDelete) Where(ps ...predicate.RpcEndpoint) *RpcEndpointDelete {
	red.mutation.Where(ps...)
	return red
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (red *RpcEndpointDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(red.hooks) == 0 {
		affected, err = red.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RpcEndpointMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			red.mutation = mutation
			affected, err = red.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(red.hooks) - 1; i >= 0; i-- {
			if red.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = red.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, red.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (red *RpcEndpointDelete) ExecX(ctx context.Context) int {
	n, err := red.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (red *RpcEndpointDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: rpcendpoint.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: rpcendpoint.FieldID,
			},
		},
	}
	if ps := red.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, red.driver, _spec)
}

// RpcEndpointDeleteOne is the builder for deleting a single RpcEndpoint entity.
type RpcEndpointDeleteOne struct {
	red *RpcEndpointDelete
}

// Exec executes the deletion query.
func (redo *RpcEndpointDeleteOne) Exec(ctx context.Context) error {
	n, err := redo.red.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rpcendpoint.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (redo *RpcEndpointDeleteOne) ExecX(ctx context.Context) {
	redo.red.ExecX(ctx)
}
