---
- name: Remove /tmp/cosmos-gov directory
  file:
    path: /tmp/cosmos-gov
    state: absent
  changed_when: false

- name: Clone cosmosgov github repository
  git:
    repo: https://{{ github_access_token }}@github.com/shifty11/cosmos-gov.git
    dest: /tmp/cosmos-gov
    clone: yes
    update: no
  become: yes
  become_user: cosmosgov

- name: Remove /etc/cosmosgov/cosmos-gov directory
  file:
    path: /etc/cosmosgov/cosmos-gov
    state: absent
  changed_when: false

- name: Copy cosmos-gov repo
  copy:
    src: /tmp/cosmos-gov
    dest: /etc/cosmosgov
    remote_src: true
  become: yes
  become_user: cosmosgov

- name: Start cosmosgov-data service
  systemd:
    name: cosmosgov-data
    state: restarted
    daemon_reload: true
    enabled: true
  changed_when: false

- name: Start cosmosgov-telegram service
  systemd:
    name: cosmosgov-telegram
    state: restarted
    daemon_reload: true
    enabled: true
  changed_when: false

- name: Start cosmosgov-discord service
  systemd:
    name: cosmosgov-discord
    state: restarted
    daemon_reload: true
    enabled: true
  changed_when: false

- name: Start cosmosgov-grpc service
  systemd:
    name: cosmosgov-grpc
    state: restarted
    daemon_reload: true
    enabled: true
  changed_when: false
