---
- name: Clone cosmosgov github repository
  git:
    repo: https://{{ github_access_token }}@github.com/shifty11/cosmos-gov.git
    dest: /etc/cosmosgov/cosmos-gov
    clone: yes
    update: yes
  become: yes
  become_user: cosmosgov

- name: Start cosmosgov-data service
  systemd:
    name: cosmosgov-data
    state: restarted
    daemon_reload: true
    enabled: true
  changed_when: false

- name: Start cosmosgov-telegram service
  systemd:
    name: cosmosgov-telegram
    state: restarted
    daemon_reload: true
    enabled: true
  changed_when: false

- name: Start cosmosgov-discord service
  systemd:
    name: cosmosgov-discord
    state: restarted
    daemon_reload: true
    enabled: true
  changed_when: false

